---
title: "Explore R2R hab changs"
author: "Erin Cain"
date: "7/23/2021"
output: 
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width=15, fig.height=8)
library(tidyverse)
library(lubridate)
```


## Spawning Habitat 
```{r}
baseline <- DSMhabitat::fr_spawn$r_to_r_baseline %>% DSMhabitat::square_meters_to_acres()
# run_river_without_proj_catalog_added <- DSMhabitat::fr_spawn$run_of_river %>% DSMhabitat::square_meters_to_acres()
run_of_river <- DSMhabitat::fr_spawn$max_flow_w_hab_projects %>% DSMhabitat::square_meters_to_acres()
tmh <- DSMhabitat::fr_spawn$r_to_r_tmh %>% DSMhabitat::square_meters_to_acres()
ror_tmh <- DSMhabitat::fr_spawn$run_of_river_tmh %>% DSMhabitat::square_meters_to_acres()

spawn <- expand_grid(
  watershed = factor(DSMscenario::watershed_labels, 
                     levels = DSMscenario::watershed_labels),
  month = 1:12,
  year = 1979:2000) %>% 
  arrange(year, month, watershed) %>% 
  mutate(
    baseline = as.vector(baseline),
    # run_river_without_proj_catalog_added = as.vector(run_river_without_proj_catalog_added),
    run_of_river = as.vector(run_of_river),
    tmh = as.vector(tmh), 
    ror_tmh = as.vector(ror_tmh)) |> glimpse()

spawn %>% 
  transmute(watershed, date = ymd(paste(year, month, 1)), baseline, run_of_river, tmh, ror_tmh) %>% 
  filter(!(watershed %in% c('Sutter Bypass', 'Yolo Bypass', "Upper-mid Sacramento River", "Lower-mid Sacramento River", "Lower Sacramento River", "San Joaquin River"))) %>% 
  gather(version, acres, -watershed, -date)  %>% 
  ggplot(aes(date, acres, color = version)) +
  geom_line(alpha = .75) +
  facet_wrap(~watershed, scales = 'free_y') + 
  theme_minimal()
```


  
## Fry Habitat 
```{r}
baseline <- DSMhabitat::fr_fry$r_to_r_baseline %>% DSMhabitat::square_meters_to_acres()
# run_river_without_proj_catalog_added <- DSMhabitat::fr_spawn$run_of_river %>% DSMhabitat::square_meters_to_acres()
run_of_river <- DSMhabitat::fr_fry$max_flow_w_hab_projects %>% DSMhabitat::square_meters_to_acres()
tmh <- DSMhabitat::fr_fry$r_to_r_tmh %>% DSMhabitat::square_meters_to_acres()
ror_tmh <- DSMhabitat::fr_fry$run_of_river_tmh %>% DSMhabitat::square_meters_to_acres()

fry <- expand_grid(
  watershed = factor(DSMscenario::watershed_labels, 
                     levels = DSMscenario::watershed_labels),
  month = 1:12,
  year = 1980:2000) %>% 
  arrange(year, month, watershed) %>% 
  mutate(
    baseline = as.vector(baseline),
    # run_river_without_proj_catalog_added = as.vector(run_river_without_proj_catalog_added),
    run_of_river = as.vector(run_of_river),
    tmh = as.vector(tmh), 
    ror_tmh = as.vector(ror_tmh)) |> glimpse()

fry %>% 
  transmute(watershed, date = ymd(paste(year, month, 1)), baseline, run_of_river, tmh, ror_tmh) %>% 
  filter(!(watershed %in% c('Sutter Bypass', 'Yolo Bypass'))) %>% 
  gather(version, acres, -watershed, -date)  %>% 
  ggplot(aes(date, acres, color = version)) +
  geom_line() +
  facet_wrap(~watershed, scales = 'free_y')
```


## Juvenile Habitat
```{r}
baseline <- DSMhabitat::fr_juv$r_to_r_baseline %>% DSMhabitat::square_meters_to_acres()
# run_river_without_proj_catalog_added <- DSMhabitat::fr_spawn$run_of_river %>% DSMhabitat::square_meters_to_acres()
run_of_river <- DSMhabitat::fr_juv$max_flow_w_hab_projects %>% DSMhabitat::square_meters_to_acres()
tmh <- DSMhabitat::fr_juv$r_to_r_tmh %>% DSMhabitat::square_meters_to_acres()
ror_tmh <- DSMhabitat::fr_juv$run_of_river_tmh %>% DSMhabitat::square_meters_to_acres()

juv <- expand_grid(
  watershed = factor(DSMscenario::watershed_labels, 
                     levels = DSMscenario::watershed_labels),
  month = 1:12,
  year = 1980:2000) %>% 
  arrange(year, month, watershed) %>% 
  mutate(
    baseline = as.vector(baseline),
    # run_river_without_proj_catalog_added = as.vector(run_river_without_proj_catalog_added),
    run_of_river = as.vector(run_of_river),
    tmh = as.vector(tmh), 
    ror_tmh = as.vector(ror_tmh)) |> glimpse()

juv %>% 
  transmute(watershed, date = ymd(paste(year, month, 1)), baseline, run_of_river, tmh, ror_tmh) %>% 
  filter(!(watershed %in% c('Sutter Bypass', 'Yolo Bypass'))) %>% 
  gather(version, acres, -watershed, -date)  %>% 
  ggplot(aes(date, acres, color = version)) +
  geom_line() +
  facet_wrap(~watershed, scales = 'free_y')
```



## Floodplain Habitat 
```{r}
baseline <- DSMhabitat::fr_fp$r_to_r_baseline %>% DSMhabitat::square_meters_to_acres()
# run_river_without_proj_catalog_added <- DSMhabitat::fr_spawn$run_of_river %>% DSMhabitat::square_meters_to_acres()
run_of_river <- DSMhabitat::fr_fp$max_flow_w_hab_projects %>% DSMhabitat::square_meters_to_acres()
tmh <- DSMhabitat::fr_fp$r_to_r_tmh %>% DSMhabitat::square_meters_to_acres()
ror_tmh <-  DSMhabitat::fr_fp$run_of_river_tmh %>% DSMhabitat::square_meters_to_acres()

fp <- expand_grid(
  watershed = factor(DSMscenario::watershed_labels, 
                     levels = DSMscenario::watershed_labels),
  month = 1:12,
  year = 1980:2000) %>% 
  arrange(year, month, watershed) %>% 
  mutate(
    baseline = as.vector(baseline),
    # run_river_without_proj_catalog_added = as.vector(run_river_without_proj_catalog_added),
    run_of_river = as.vector(run_of_river),
    tmh = as.vector(tmh), 
    ror_tmh = as.vector(ror_tmh)) |> glimpse()

fp %>% 
  transmute(watershed, date = ymd(paste(year, month, 1)), baseline, run_of_river, tmh, ror_tmh) %>% 
  filter(!(watershed %in% c('Sutter Bypass', 'Yolo Bypass'))) %>% 
  filter(watershed == "Lower-mid Sacramento River") |> 
  gather(version, acres, -watershed, -date)  %>% 
  ggplot(aes(date, acres, color = version)) +
  geom_line(alpha = .75) +
  facet_wrap(~watershed, scales = 'free_y') + 
  theme_minimal()
```

Something funky going on with Lower-mid sac fp habitat


## Delta Habitat 
```{r}
sit_habitat <- DSMhabitat::delta_habitat$sit_habitat[,, "North Delta"] %>% DSMhabitat::square_meters_to_acres()
baseline <- DSMhabitat::delta_habitat$r_to_r_baseline[,, "North Delta"] %>% DSMhabitat::square_meters_to_acres()
run_of_river <- DSMhabitat::delta_habitat$max_flow_w_hab_projects[,, "North Delta"] %>% DSMhabitat::square_meters_to_acres()
tmh <- DSMhabitat::delta_habitat$r_to_r_tmh[,, "North Delta"] %>% DSMhabitat::square_meters_to_acres()
ror_tmh <- DSMhabitat::delta_habitat$run_of_river_tmh[,, "North Delta"] %>% DSMhabitat::square_meters_to_acres()

delta <- expand_grid(
  watershed = c("North Delta"),
  month = 1:12,
  year = 1980:2000) %>% 
  arrange(year, month, watershed) %>% 
  mutate(
    sit_habitat = as.vector(sit_habitat),
    baseline = as.vector(baseline),
    run_of_river = as.vector(run_of_river),
    tmh = as.vector(tmh), 
    ror_tmh = as.vector(ror_tmh)) |> glimpse()

delta %>% 
  transmute(watershed, date = ymd(paste(year, month, 1)), sit_habitat, baseline, run_of_river, tmh, ror_tmh) %>% 
  gather(version, acres, -watershed, -date)  %>% 
  ggplot(aes(date, acres, color = version, linetype = version)) +
  geom_line(alpha = .75) +
  facet_wrap(~watershed, scales = 'free_y') + 
  theme_minimal()
```