---
title: "Max Theoretical Habitat to CVPIA SIT Habitat Comparison"
author: "Maddee Rubenson (FlowWest)"
date: "`r Sys.Date()`"
output:
  rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(DSMhabitat)
library(lubridate)

# fall run:
all_max_habitat_fall <- readRDS('../all_habitat_data_for_tmh_inputs_fall_run.rdata') |> 
  mutate(run = "fall run")

all_max_habitat_winter_spring <- readRDS('../all_habitat_data_for_tmh_inputs_spring_winter_run.rdata') |> 
  mutate(run = "winter and spring run")

cvpia_habitat_data <- read_csv('../CVPIA_habitat_data.csv') |> 
   #select(-c(spwn_flow, rear_flow, flood_flow)) |> 
   mutate(watershed = ifelse(watershed == "San Joaquin River", "Lower San Joaquin River", watershed))
```

## Fall Run

```{r}

cvpia_habitat_data |> 
  glimpse()

all_max_habitat_fall |> 
  glimpse()

all_habitat_data <- full_join(cvpia_habitat_data, all_max_habitat_fall) |> 
  glimpse()

all_perc_increase <- all_habitat_data |> 
  mutate(instream_rearing_juv_perc_increase = (max_rearing_acres - rear_acres_juv)/rear_acres_juv * 100,
         instream_rearing_fry_perc_increase = (max_rearing_acres - rear_acres_fry)/rear_acres_fry * 100,
         spwn_perc_increase = (max_spawning_acres - spwn_acres)/spwn_acres * 100,
         flood_perc_increase = (max_floodplain_acres - flood_acres)/flood_acres * 100) |> 
  select(watershed, rear_acres_juv, rear_acres_fry, max_rearing_acres, 
         instream_rearing_juv_perc_increase, instream_rearing_fry_perc_increase,
         spwn_acres, max_spawning_acres, spwn_perc_increase, 
         flood_acres, max_floodplain_acres, flood_perc_increase)  |> 
  mutate(flag1 = ifelse(instream_rearing_juv_perc_increase < 0, "flag: juv", NA),
         flag2 = ifelse(instream_rearing_fry_perc_increase < 0, "flag: fry", NA),
         flag3 = ifelse(flood_perc_increase < 0, "flag: flood", NA),
         flag4 = ifelse(spwn_perc_increase < 0, "flag: spwn", NA)) 
  #write_csv('habitat_markdowns/data_output/max_hab_perc_increases.csv')
```

### Fry Rearing Differences:

```{r}
all_perc_increase |> 
  select(watershed, rear_acres_fry, max_rearing_acres, instream_rearing_fry_perc_increase,
         flag1:flag4) |> 
  knitr::kable(digits = 1) 
```

### Juvenile Rearing Differences:

```{r}
all_perc_increase |> 
  select(watershed, rear_acres_juv, max_rearing_acres, instream_rearing_fry_perc_increase, flag1:flag4) |> 
  knitr::kable(digits = 1)

ggplot(all_habitat_data) + 
  geom_col(aes(x = watershed, y = max_rearing_acres, fill =  "max values"),  alpha = 0.75) +
  geom_col(aes(x = watershed, y = rear_acres_juv, fill = "SIT values"),  alpha = 0.5) +
  ggtitle('juvenile rearing acres') +
  coord_flip() +
  theme_minimal() +
  theme(legend.position="top", 
        legend.title = element_blank())


ggplot(all_habitat_data) + 
  geom_col(aes(x = watershed, y = max_rearing_acres, fill =  "max values"),  alpha = 0.75) +
  geom_col(aes(x = watershed, y = rear_acres_fry, fill = "SIT values"),  alpha = 0.5) +
  ggtitle('fry rearing acres') +
  coord_flip() +
  theme_minimal() +
  theme(legend.position="top", 
        legend.title = element_blank())
```

### Spawning Differences:

```{r}
all_perc_increase |> 
  select(watershed, spwn_acres, max_spawning_acres, spwn_perc_increase, flag1:flag4) |> 
  knitr::kable(digits = 1)

all_habitat_data |> 
  filter(!is.na(spwn_acres)) |> 
  ggplot() + 
  geom_col(aes(x = watershed, y = max_spawning_acres, fill =  "Max Habitat"),  alpha = 0.75) +
  geom_col(aes(x = watershed, y = spwn_acres, fill = "SIT Habitat"),  alpha = 0.5) +
  ggtitle('Spawning Acres') + 
  ylab('acres') + 
  coord_flip() +
  theme_minimal() + 
  theme(legend.position="top", 
        legend.title = element_blank())

```

### Floodplain Differences:

```{r}
all_perc_increase |> 
  select(watershed, flood_acres, max_floodplain_acres, flood_perc_increase, flag1:flag4) |> 
  knitr::kable(digits = 1)

ggplot(all_habitat_data) + 
  geom_col(aes(x = watershed, y = max_floodplain_acres, fill =  "max values"), alpha = 0.75) +
  geom_col(aes(x = watershed, y = flood_acres, fill = "SIT values"), alpha = 0.75) +
  ggtitle('floodplain acres') +
  coord_flip() + 
  theme_minimal() +
  theme(legend.position="top", 
        legend.title = element_blank())
```

### Compare Max Habitat across Runs 

```{r}

all_max_hab <- all_max_habitat_fall |> bind_rows(all_max_habitat_winter_spring)

ggplot(all_max_hab) + 
  geom_col(aes(x = watershed, y = max_floodplain_acres, fill =  run), alpha = 0.75, 
           position = "dodge") +
  #geom_col(aes(x = watershed, y = max_floodplain_acres, fill = "SIT values"), alpha = 0.75) +
  ggtitle('floodplain acres') +
  coord_flip() + 
  theme_minimal() +
  theme(legend.position="top", 
        legend.title = element_blank())


```
